---
- name: Проверка данных и динамическое создание хоста
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Проверить, что IP-адрес передан
      ansible.builtin.fail:
        msg: "Ошибка: Вы не указали IP-адрес в форме Survey!"
      when: target_host is not defined or target_host | trim == ""

    - name: Добавить динамические хосты в память Ansible
      ansible.builtin.add_host:
        name: "{{ item | trim }}"
        group: "dynamic_hosts"
      loop: "{{ target_host.split(',') }}"

- name: Установка Midnight Commander
  hosts: dynamic_hosts
  gather_facts: false
  become: true
  tasks:
    - name: Установить пакет mc
      ansible.builtin.package:
        name: mc
        state: present
